### ISSUE TITLE
Metadata keys containing periods are unstrippable

### ISSUE THREAD

**Issue by baldwint** [kynan/nbstripout#143]
I work with databricks notebooks, which (when exported to the ipynb format) add metadata fields with keys:

- `application/vnd.databricks.v1+cell`
- `application/vnd.databricks.v1+notebook`

at the cell and notebook levels, respectively.

Stripping these does not work using this tool because nbstripout interprets the period `.` as a dictionary nesting delimiter when I pass these names as arguments to the extra keys argument.

For example, `nbstripout --extra-keys='cell.metadata.application/vnd.databricks.v1+cell metadata.application/vnd.databricks.v1+notebook' my_notebook.ipynb` will not work.

I have a modified version of nbstripout that fixes the issue and I will open a pull request for it.

**Comment by robertofierimonte** [comment]
Hey @kynan how do I enable these extra keys filters for period keys when using the tools as a pre-commit?

This is my pre-commit config but it does not seem to strip out Databricks metadata:
`- repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
        args: ["--extra-keys='metadata.application/vnd.databricks.v1+notebook cell.metadata.application/vnd.databricks.v1+cell'"]`

**Comment by kynan** [comment]
@robertofierimonte Not sure what might be going on there. Do you have a sample Databricks notebook to reproduce this issue?

**Comment by solita-robertofierimonte** [comment]
Hi @kynan sorry for the delay. Please find one. 

With nbstripout 0.8.1 I am able to strip the Databricks metadata through command like:

`ls -1 notebooks/*.ipynb | xargs -n 1 -I % nbstripout % --extra-keys='metadata.application/vnd.databricks.v1+notebook cell.metadata.application/vnd.databricks.v1+cell'`

But I cannot do so through pre-commit:

```
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys="metadata.application/vnd.databricks.v1+notebook cell.metadata.application/vnd.databricks.v1+cell"']
```

**Comment by robertofierimonte** [comment]
Hi @kynan sorry for the delay. Please find one (remove .txt extension as I was unable to upload a .ipynb file)

With nbstripout 0.8.1 I am able to strip the Databricks metadata through command like:

`ls -1 notebooks/*.ipynb | xargs -n 1 -I % nbstripout % --extra-keys='metadata.application/vnd.databricks.v1+notebook cell.metadata.application/vnd.databricks.v1+cell'`

But I cannot do so through pre-commit:

```
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args: ['--extra-keys="metadata.application/vnd.databricks.v1+notebook cell.metadata.application/vnd.databricks.v1+cell"']
```

[Test_Streaming.ipynb.txt](https://github.com/user-attachments/files/19027225/Test_Streaming.ipynb.txt)
